services:

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    networks:
      - app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              
  web:
    build: ./web
    ports:
      - "80:80"
    networks:
      - app

networks:
  app:
    driver: bridge